### ISSUE TITLE
Euclidean.dist should probably be avoided

### ISSUE THREAD

**Issue by eric-wieser** [trishullab/PutnamBench#165]
Some fairly low priority feedback; this formalization

https://github.com/trishullab/PutnamBench/blob/0d6e0217acb74aba14dcdf6b217bbdf14ab81628/lean4/src/putnam_1962_a3.lean#L11-L13

should probably not be using `Euclidean.dist`, which [doesn't do](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/What.20is.20docs.23euclidean.2Edist.3F/near/282605550)  [what you'd expect](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/Euclidean.20distance.20on.20reals/near/423820434).

**Comment by GeorgeTsoukalas** [comment]
What would you recommend as a substitute? As far as we know, Dist.dist x y seems to compute $\|x-y\|_{\infty}$ but I could be wrong on this, the output of #eval seems to indicate it. We can of course define the Euclidean distance manually.

**Comment by GeorgeTsoukalas** [comment]
Thanks for the suggestion! After going through the benchmark there were about ~40 problems which were making use of Euclidean.dist and also things like Metric.ball and Metric.sphere which should now use the right notion of distance. Keeping the issue open as there as a problem or two more to be modified from this bunch. Let me know if you have notice other issues!

**Comment by eric-wieser** [comment]
(in #188, I assume)

**Comment by GeorgeTsoukalas** [comment]
For the most part, yeah. Another problem (2019_b1) appears in #189, which should be all of them.
