### ISSUE TITLE
Evaluation of Formal Proofs

### ISSUE THREAD

**Issue by sivakishoresk** [trishullab/PutnamBench#168]
Many of the theorem statements does not have formal proofs(they have the sorry tags). If I have a generated proof for a theorem how should I evaluate it, even if we have a predicted proof and ground truth proof, how do I go for semantic evaluation between these two.
Someone please help me with this.

**Comment by GeorgeTsoukalas** [comment]
Hi,

The nice feature about the statements being written in interactive theorem provers like Lean, Isabelle, and Coq is that you do not need to compare to a ground truth proof. Semantic evaluation is also unnecessary, all you need to know is whether the proof you generated compiles without error in the language. I would recommend looking through the following Lean introduction: https://leanprover-community.github.io/mathematics_in_lean/. This should give a sense of how it works.

There are tools to interact with Lean such as https://leandojo.org/ and https://github.com/trishullab/copra.
