### ISSUE TITLE
InternLM-Math solves 4 problems with answers in LEAN 4.

### ISSUE THREAD

**Issue by objecti0n** [trishullab/PutnamBench#169]
How do I update our results to your benchmark?

**Comment by amit9oct** [comment]
Can you share your results here? It would be great if you could share the proofs and possibly the code to your repository for generating these proofs.

**Comment by GeorgeTsoukalas** [comment]
In the future, all verifications of potential leaderboard results should be handled in private communications so as to reduce potential for test-set leakage for LLM based approaches.

**Comment by oxysoft** [comment]
Hi @GeorgeTsoukalas, actually there is a problem - it's not indicated clearly anywhere on this project or the leaderboard page how we can get in contact. Looking forward to share my results!

**Comment by GeorgeTsoukalas** [comment]
Apologies for the delay. We are deliberating internally the best way to display results on the leaderboard with respect to allocated compute budget. We will come to a consensus and add your results soon, thanks for your patience!

**Comment by GeorgeTsoukalas** [comment]
Hi, it is not immediately clear which model size you used? Can you share these details? I am ok with adding it since there is an associated publication although the exact model itself is a later checkpoint and does not seem to be open sourced (I will not be able to indicate it as an open-source result for this reason).

**Comment by GeorgeTsoukalas** [comment]
We've added your result to the leaderboard (proofs look correct). Let us know if you have further results/updates on the open-sourced nature either through an issue (don't include proofs) or through private communications (I have added my email to the main README for that). Thanks!
