### ISSUE TITLE
Successful proofs from leaderboard available?

### ISSUE THREAD

**Issue by brando90** [trishullab/PutnamBench#213]
I was wondering if the successful proofs from leaderboard available?

Thanks in advance!

**Comment by GeorgeTsoukalas** [comment]
Hi Brando,

In an effort to reduce possible leakage into LLM training data we have avoided publicly mentioning any proofs generating by attempted methods, except in the paper: https://arxiv.org/abs/2407.11214.

**Comment by brando90** [comment]
Oh no worries! Thank you

**Comment by eric-wieser** [comment]
While including the proofs in the leaderboard is indeed risky, perhaps the names of the theorems should be included?

**Comment by GeorgeTsoukalas** [comment]
I think this is a good point, I'll collect these and include them somewhere in an upcoming PR. Perhaps as part of `docs/result.json`.

**Comment by eric-wieser** [comment]
Perhaps also the commit information should be recorded in that same json file; which would make it possible to determine if the problem has been fixed since it was solved.

**Comment by GeorgeTsoukalas** [comment]
Yup we can record this information going forward. I will try to get that info for some of the more recent entries (and one which should appear soon-ish)
